services:
  - type: web
    name: opendevin-agent
    plan: free
    env: docker
    # Esto es nuevo: Le decimos a qué grupo de secrets tiene que conectarse.
    envVarGroups:
      - name: GeminiCredentials # ¡Este nombre es importante!
    # El resto de la configuración del servicio
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 3001
      - key: LLM_MODEL
        value: gemini/gemini-1.5-flash-latest
      - key: WORKSPACE_BASE
        value: /app/opendevin/workdir
      - key: SANDBOX_TYPE
        value: exec
